CC = gcc
LIB = -lsocket -lnsl -lpthread

all: myftpserver.c myftpclient.c
	${CC} -o myftpserver myftpserver.c myftp.c ${LIB}
	${CC} -o myftpclient myftpclient.c myftp.c ${LIB}

clean:
	rm myftpserver
	rm myftpclient
